{{- if .Values.secrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ipfix-generator.fullname" . }}
  labels:
    {{- include "ipfix-generator.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- range $name, $value := .Values.secrets }}
  {{ $name }}: {{ $value | quote }}
  {{- end }}
{{- end }}
